Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
  - 'test/**/*'
  - 'db/**/*'
  - 'vendor/**/*'
  - 'lib/**/*'
  - 'config/**/*'
  - 'tmp/**/*'
  - 'bin/**/*'
  - 'spec/rails_helper.rb'
  - 'spec/spec_helper.rb'

Metrics/LineLength:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/TrailingBlankLines:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: rails

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Layout/EmptyLineBetweenDefs:
  # Can be array to specify minimum and maximum number of empty lines, e.g. [1, 2]
  NumberOfEmptyLines: [1, 2]

Layout/AlignHash:
  Enabled: false

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/BracesAroundHashParameters:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/NumericPredicate:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Naming/MemoizedInstanceVariableName:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 25

Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'
